### ISSUE TITLE
setValue at /data/default/-failed: DatabaseError: Permission denied

### ISSUE THREAD

**Issue by li2** [googlecodelabs/androidthings-surveybox#2]
W/RepoOperation: setValue at /data/default/-LUMnYdmdG3dE3SBN2Ri failed: DatabaseError: 
    Permission denied

When I create the Firebase project, the rules of the database on Firebase console is :
![image](https://user-images.githubusercontent.com/6058601/50378712-8b135980-068c-11e9-9d9b-6ec9ee0cf72a.png)

it's different with codelab:
https://codelabs.developers.google.com/codelabs/surveybox/index.html?index=..%2F..index#4:
![image](https://user-images.githubusercontent.com/6058601/50378705-7cc53d80-068c-11e9-9e2b-08750b256023.png)

Then I changed the rule to codelab version, but firebase was not recognizing:

    Error saving rules - Line 1: mismatched input '{' expecting {'function', 'service', 'rules_version'}

https://stackoverflow.com/questions/29901935/android-firebase-setvalue-permission-denied/37963998#37963998

https://stackoverflow.com/questions/37424544/firebase-database-permission-denied-with-read-write-permissions-set-to-true/37428000

**Comment by li2** [comment]
Sorry It's my fault, need to change database to `Realtime Database`:

![image](https://user-images.githubusercontent.com/6058601/50378833-5ead0c80-068f-11e9-9c8d-5d67a6eb60c9.png)

https://github.com/firebase/friendlychat-ios/issues/12#issuecomment-410793096

**Comment by Eric-wu0805** [comment]
DatabaseError: Permission denied 
What to do?
